# Generated by Django 4.2.20 on 2025-04-19 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateField(verbose_name='data da atualização')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'ordering': ['data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(verbose_name='descrição da função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['funcao'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('padroeiro', models.CharField(max_length=100, verbose_name='padroeiro do grupo')),
                ('quantidade_membros', models.IntegerField(default=0, editable=False, verbose_name='quantidade de membros')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IndiceComprometimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(max_length=100, verbose_name='descrição do índice de comprometimento')),
            ],
            options={
                'verbose_name': 'Índice de Comprometimento',
                'verbose_name_plural': 'Índices de Comprometimento',
                'ordering': ['indice'],
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(max_length=100, verbose_name='descrição da situação')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
                'ordering': ['situacao'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_investidura', models.DateField(verbose_name='data de investidura')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['data_investidura'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('resumo', models.TextField(max_length=300, verbose_name='resumo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('nome_pai', models.CharField(max_length=100, verbose_name='nome do pai')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='nome da mãe')),
                ('sacramentos_recebidos', models.CharField(max_length=200, verbose_name='sacramentos recebidos')),
                ('atuacao_pastorais', models.CharField(max_length=200, verbose_name='atuações em pastorais ')),
                ('disponibilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.disponibilidade', verbose_name='disponibilidade ')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcao', verbose_name='função ')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.grupo', verbose_name='grupo ')),
                ('indice_comprometimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.indicecomprometimento', verbose_name='índice de comprometimento ')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.situacao', verbose_name='situação ')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma', verbose_name='turma ')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(max_length=200, verbose_name='observação')),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.atualizacao', verbose_name='atualização')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.membro', verbose_name='membro')),
            ],
            options={
                'verbose_name': 'Atualização de Membro',
                'verbose_name_plural': 'Atualizações de Membros',
                'ordering': ['membro'],
            },
        ),
    ]
