# Generated by Django 4.2.20 on 2025-08-07 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20, unique=True, verbose_name='Dia e Horário com celebração')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100, unique=True, verbose_name='função')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição da função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['funcao'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('padroeiro', models.CharField(max_length=100, verbose_name='padroeiro do grupo')),
                ('quantidade_membros', models.IntegerField(default=0, verbose_name='quantidade de membros')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IndiceComprometimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição do índice de comprometimento')),
            ],
            options={
                'verbose_name': 'Índice de Comprometimento',
                'verbose_name_plural': 'Índices de Comprometimento',
                'ordering': ['indice'],
            },
        ),
        migrations.CreateModel(
            name='Pastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome da pastoral')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='sigla da pastoral')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa/Inativa')),
            ],
            options={
                'verbose_name': 'Pastoral',
                'verbose_name_plural': 'Pastorais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição da situação')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
                'ordering': ['situacao'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_turma', models.IntegerField(default=0, unique=True, verbose_name='número da turma')),
                ('data_investidura', models.DateField(verbose_name='data de investidura')),
                ('grupo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cadastros.grupo', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['data_investidura'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('resumo', models.TextField(blank=True, max_length=300, null=True, verbose_name='resumo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='endereço')),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome do pai')),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome da mãe')),
                ('sacramentos', models.CharField(choices=[('B', 'Somente o Batismo'), ('E', 'Somente a Eucaristia'), ('BE', 'Batismo e Eucaristia'), ('T', 'Todos concluídos')], default='T', max_length=2, verbose_name='Sacramentos de Iniciação Cristã')),
                ('observacao', models.TextField(blank=True, max_length=300, null=True, verbose_name='observações')),
                ('atuacao_pastorais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pastoral', verbose_name='atuações em pastorais')),
                ('disponibilidade', models.ManyToManyField(to='cadastros.disponibilidade', verbose_name='disponibilidade')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcao', verbose_name='função')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.grupo', verbose_name='grupo')),
                ('indice_comprometimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.indicecomprometimento', verbose_name='índice de comprometimento')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.situacao', verbose_name='situação')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma', verbose_name='turma')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateField(default='2019-08-17', verbose_name='data da atualização')),
                ('observacao', models.TextField(blank=True, max_length=200, null=True, verbose_name='observação')),
                ('membro', models.ManyToManyField(to='cadastros.membro', verbose_name='membro')),
            ],
            options={
                'verbose_name': 'Atualização de Membro',
                'verbose_name_plural': 'Atualizações de Membros',
                'ordering': ['data_atualizacao'],
            },
        ),
    ]
