# Generated by Django 4.2.20 on 2025-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atualizacaomembro',
            name='atualizacao',
        ),
        migrations.AddField(
            model_name='atualizacaomembro',
            name='data_atualizacao',
            field=models.DateField(default='2019-08-17', verbose_name='data da atualização'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='quantidade_membros',
            field=models.IntegerField(default=0, verbose_name='quantidade de membros'),
        ),
        migrations.DeleteModel(
            name='Atualizacao',
        ),
    ]
