# Generated by Django 4.2.20 on 2025-04-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_atualizacaomembro_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome da pastoral')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='sigla da pastoral')),
            ],
            options={
                'verbose_name': 'Pastoral',
                'verbose_name_plural': 'Pastorais',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='membro',
            name='sacramentos_recebidos',
        ),
        migrations.AddField(
            model_name='membro',
            name='sacramentos',
            field=models.CharField(choices=[('B', 'Somente o Batismo'), ('C', 'Somente a Crisma'), ('E', 'Somente a Eucaristia'), ('BE', 'Batismo e Eucaristia'), ('T', 'Todos concluídos')], default='B', max_length=2, verbose_name='Sacramentos de Iniciação Cristã'),
        ),
        migrations.AddField(
            model_name='turma',
            name='grupo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cadastros.grupo', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='atuacao_pastorais',
            field=models.CharField(max_length=200, verbose_name='atuações em pastorais'),
        ),
        migrations.RemoveField(
            model_name='membro',
            name='disponibilidade',
        ),
        migrations.AlterField(
            model_name='membro',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcao', verbose_name='função'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.grupo', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='indice_comprometimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.indicecomprometimento', verbose_name='índice de comprometimento'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.situacao', verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma', verbose_name='turma'),
        ),
        migrations.AddField(
            model_name='membro',
            name='disponibilidade',
            field=models.ManyToManyField(blank=True, to='cadastros.disponibilidade', verbose_name='disponibilidade'),
        ),
    ]
