# Generated by Django 4.2.20 on 2025-04-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_pastoral_remove_membro_sacramentos_recebidos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atualizacaomembro',
            options={'ordering': ['data_atualizacao'], 'verbose_name': 'Atualização de Membro', 'verbose_name_plural': 'Atualizações de Membros'},
        ),
        migrations.AddField(
            model_name='membro',
            name='observacao',
            field=models.TextField(blank=True, max_length=300, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='pastoral',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativa/Inativa'),
        ),
        migrations.RemoveField(
            model_name='atualizacaomembro',
            name='membro',
        ),
        migrations.AlterField(
            model_name='membro',
            name='atuacao_pastorais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pastoral', verbose_name='atuações em pastorais'),
        ),
        migrations.AddField(
            model_name='atualizacaomembro',
            name='membro',
            field=models.ManyToManyField(to='cadastros.membro', verbose_name='membro'),
        ),
    ]
