# Generated by Django 4.2.20 on 2025-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_turma_num_turma_alter_membro_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.CharField(max_length=20, unique=True, verbose_name='Dia e Horário com celebração'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='funcao',
            field=models.CharField(max_length=100, unique=True, verbose_name='função'),
        ),
        migrations.AlterField(
            model_name='indicecomprometimento',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, verbose_name='descrição do índice de comprometimento'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, verbose_name='descrição da situação'),
        ),
    ]
