# Generated by Django 4.2.20 on 2025-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_disponibilidade_dia_semana_alter_funcao_funcao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaomembro',
            name='observacao',
            field=models.TextField(blank=True, max_length=200, verbose_name='observação'),
        ),
    ]
