# Generated by Django 4.2.20 on 2025-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_atualizacaomembro_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaomembro',
            name='observacao',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='indicecomprometimento',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição do índice de comprometimento'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nome da mãe'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nome do pai'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='observacao',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='resumo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição da situação'),
        ),
    ]
