# Generated by Django 4.2.20 on 2025-04-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_atualizacaomembro_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição da função'),
        ),
    ]
